#!/usr/bin/env escript

main([String]) ->
    try
        N = list_to_integer(String),
        if
            N < 1 -> usage(), halt(1);
            true -> nil
        end,
        {_S, B} = control : init(lcr, N, topology : ring(N),
                                 fun(X) -> X + (N + 1) * rand : uniform(10 * N)  end),
        B(start),
        receive
           false -> ok
        end
    catch
        _:_ -> usage()
    end;
main(_) -> usage().

usage() -> io:format("usage: lcr n, with n >= 1\n"), halt(1).



